### ISSUE TITLE
link for speakers is incorrect

### ISSUE THREAD

**Issue by flowolf** [linuxtage/glt-companion#12]
pretalx has unique ids for speakers.

the format is like this:
https://pretalx.linuxtage.at/glt19/speaker/7AUMGB/

https://pretalx.linuxtage.at/glt19/speaker/[UNIQUE_ID]/

the unique ID is not available in the frab compatible schedule format. maybe needs a fix in pretalx too.

**Comment by Rufus125** [comment]
quickfix: set the info icon to invisible

**Comment by Rufus125** [comment]
Create an issue for pretalx: https://github.com/pretalx/pretalx/issues/641
