### ISSUE TITLE
link for talk is incorrect

### ISSUE THREAD

**Issue by flowolf** [linuxtage/glt-companion#13]
the link to the talk info is incorrect. it should be in the format

eg: https://pretalx.linuxtage.at/glt19/talk/ZJVDJV/

https://pretalx.linuxtage.at/glt19/talk/[UNIQUE_ID]/

the URL is passed as info of an event.
`<event>
...
  <url>[URL]</url>
...
</event>`

**Comment by Rufus125** [comment]
For this to work I had to alter the DB schema. So all DB data is lost. However, this is not too bad, because the conference data should be refreshed anyhow.
