### ISSUE TITLE
Rooms and buildings must be created

### ISSUE THREAD

**Issue by flowolf** [linuxtage/glt-companion#14]
the current meta info for talks contains rooms and buildings that are not known. they must be created.

**Comment by Rufus125** [comment]
layout/item_event.xml
Change line 54:  tools:text="Saturday, 09:30 - 09:55 | HS16" /> 

at/linuxtage/companion/model/Building.java

**Comment by Rufus125** [comment]
Mapping Room - Building has been added
Building Unknown is not localized. I do not know how to implement this correctly
