### ISSUE TITLE
fix logo

### ISSUE THREAD

**Issue by flowolf** [linuxtage/glt-companion#16]
the linuxtage logo should be on top of the navigation bar.

**Comment by Rufus125** [comment]
The file drawable/fosdem_title.xml needs to be adapted to this https://gitlab.linuxtage.at/GLT/Grafik/blob/master/Logo/glt_logo_mit_tux.svg
Convert with this online tool: https://a-student.github.io/SvgToVectorDrawableConverter.Web/
fosdem_title is used in layout/navigation_header.xml
changed the scale type
However, the file is a bit cropped currently
