### ISSUE TITLE
While copying text from GLT Companion, it crashes. 

### ISSUE THREAD

**Issue by PeerzadaZeeshan** [linuxtage/glt-companion#8]
#### Expected behavior
While long press upon text in GLT companion app, want to expand the selecting area by dragging fingers, it should to be selected. 

#### Actual behavior
While selecting the text in GLT Companion by dragging fingers to select the area,it crashes. 

#### How to reproduce
Install app from f droid. 

Open the app

Here appears some files. 

Press on it to open. 

Long press on any word. 

Then leave finger.

Drag the selected area by your finger to select more area,it crashes. 

* Browser:GLT Companion. 
* Version:1.4.5
* Operating system:5.1.1

#### Recording Of The Bug
https://youtu.be/2gO4dCTqot4
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@peerzadazeeshan/while-copying-text-from-glt-companion-it-crashes">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by flowolf** [comment]
Thanks for the bug report. We will investigate - although I can't reproduce it right now with my Android 8.0.0.

Do you have a custom rom or any other modifications to the system?

**Comment by meisterluk** [comment]
Cannot reproduce it either on my Android 6.0 (Kernel 3.18.19+). More details required from @PeerzadaZeeshan.

**Comment by Cha0s0000** [comment]
@meisterluk @flowolf I could reproduce it on Android 5.0.0, while it happened rarely maybe with several dragging .
I just select the wrods and drag the whole selected words , as you can see below the gif , the select cursor will jump to other position , then if i go on to select some words , it will immediately crash.
![gif](https://user-images.githubusercontent.com/13085816/39338450-68f8136c-49f5-11e8-8283-59381ce432a1.gif)

**Comment by cbeyls** [comment]
Thanks for the feedback, I fixed the issue upstream

**Comment by flowolf** [comment]
Thanks @cbeyls! 🦊
