### ISSUE TITLE
Files are un-executable 

### ISSUE THREAD

**Issue by onos1** [linuxtage/glt-companion#9]
A video to display the issue

https://youtu.be/TOf58VylNk8

**Comment by meisterluk** [comment]
Cannot reproduce on my Android 6.0. Test was done with Signal (not Telegram) and builtin Calendar 6.0 (not VCalendar). I think that the issue is that VCalendar might not be able to read it.

Can you give us some information on your Android version and VCalendar version?

**Comment by onos1** [comment]
Android 7.0 was used and try using another app apart from the calendar app
